DataManagement/urls.py
from django.urls import path
from DataManagement import views

app_name = 'DataManagement'

urlpatterns = [
    path('', views.index, name = 'data'),
    path('upload/', views.data_upload, name = 'upload'),
    path('chart/<str:serial>/', views.chart, name = 'chart'),
    path('<str:proj>/<str:serial>/', views.data_get, name = 'data_get'),
]

ProjectAPSrt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('RealtimeAPS.urls')),
    path('data/', include('DataManagement.urls')),
]

RealtimeAPS/urls.py
from django.urls import path
from RealtimeAPS import views

app_name = 'RealtimeAPS'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('login/', views.login, name = 'login'),
    path('logout/', views.logout, name = 'logout'),
    path('users/', views.users, name = 'users'),
    path('users/add/', views.user_add, name = 'user_add'),
    path('users/<int:pk>/', views.user_detail, name = 'user_detail'),
    path('projects/', views.projects, name = 'projects'),
    path('projects/add/', views.project_add, name = 'project_add'),
    path('projects/<int:pk>/', views.project_detail, name = 'project_detail'),
    path('projects/<int:pk>/user_add/', views.project_user_add, name = 'assign'),
    path('projects/<int:pk>/sensor_add/', views.project_sensor_add, name = 'sensor_add'),
]

RealtimeAPS/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='info')
    companyname = models.CharField(max_length = 200, null = True)
    phone = models.CharField(max_length = 20, null = True)

    def __str__(self):
        return f"{self.user} {self.companyname} {self.phone}"

class Project(models.Model):
    name = models.CharField(max_length = 200)

    def __str__(self):
        return self.name

class UserProject(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='users')
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='projects')

    def __str__(self):
        return f"{self.user.username} {self.project.name}"

RealtimeAPS/views.py
from django.shortcuts import render, redirect
from django.contrib import auth
from django.contrib.auth.decorators import *
from RealtimeAPS.models import *
from DataManagement.models import *
from json import dumps

# Create your views here.
@login_required
def index(request):
    data = {'sensors':{}}
    if request.user.is_superuser:
        data['projects'] = Project.objects.all()
    else:
        data['projects'] = [i.project for i in UserProject.objects.filter(user = request.user)]
    for p in data['projects']:
        temp = [s.serial for s in p.sensors.all()]
        data['sensors'][p.name] = temp
    data['sensors'] = dumps(data['sensors'])
    return render(request, 'RealtimeAPS/index.html', data)

def login(request):
    if request.method == 'POST':
        form = request.POST
        username = form.get('username')
        password = form.get('password')
        user = auth.authenticate(request, username = username, password = password)
        if user:
            auth.login(request, user)
            return redirect('/')
    return render(request, 'RealtimeAPS/login.html')

def logout(request):
    auth.logout(request)
    return redirect('/')

def users(request):
    if request.user.is_superuser:
        if request.method == 'POST':
            form = request.POST
            action = form.get('action')
            if action == 'Add':
                return redirect('/users/add/')
            elif action == 'Remove':
                for x in [int(i) for i in form if i.isdigit()]:
                    User.objects.get(id = x).delete()
        data = {}
        data['users'] = User.objects.filter(is_superuser=False)
        return render(request, 'RealtimeAPS/users.html', data)
    return redirect('/')

def user_detail(request, pk):
    if request.user.is_superuser or request.user.id == pk:
        if request.method == 'POST':
            form = request.POST
            action = form.get('action')
            if action == 'Save':
                username = form.get('username')
                email = form.get('email')
                companyname = form.get('company_name')
                phone = form.get('phone')
                u = User.objects.filter(id = pk)
                info = u[0].info
                u.update(username = username, email = email)
                info.companyname = companyname
                info.phone = phone
                info.save()
        data = {}
        data['user'] = User.objects.get(id = pk)
        return render(request, 'RealtimeAPS/user_detail.html', data)
    return redirect('/')

def user_add(request):
    if request.user.is_superuser:
        if request.method == 'POST':
            form = request.POST
            username = form.get('username')
            email = form.get('email')
            password = form.get('password')
            user = User.objects.create_user(username = username, password = password, email = email, is_staff = False, is_superuser = False)
            user_info = UserInfo(user=user, companyname='', phone='')
            user_info.save()
            return redirect('/users/')
        return render(request, 'RealtimeAPS/user_add.html')
    return redirect('/')

def projects(request):
    if request.user.is_superuser:
        if request.method == 'POST':
            form = request.POST
            action = form.get('action')
            if action == 'Add':
                return redirect('/projects/add/')
            elif action == 'Remove':
                for x in [int(i) for i in form if i.isdigit()]:
                    Project.objects.get(id = x).delete()
        data = {}
        data['projects'] = Project.objects.all()
        return render(request, 'RealtimeAPS/projects.html', data)
    return redirect('/')

@login_required
def project_detail(request, pk):
    if request.user.is_superuser or (request.user in [i.user for i in UserProject.objects.filter(project_id=pk)]):
        if request.method == 'POST':
            form = request.POST
            action = form.get('action')
            if action == 'Save':
                proj_name = form.get('project_name')
                proj = Project.objects.get(id = pk)
                proj.name = proj_name
                proj.save()
            elif action == 'Cancel':
                return redirect('/projects/')
        data = {}
        data['project'] = Project.objects.get(id = pk)
        return render(request, 'RealtimeAPS/project_detail.html', data)
    return redirect('/')

def project_add(request):
    if request.user.is_superuser:
        if request.method == 'POST':
            form = request.POST
            proj_name = form.get('project_name')
            proj = Project(name=proj_name)
            proj.save()
            return redirect(f'/projects/{proj.id}/')
        return render(request, 'RealtimeAPS/project_add.html')
    return redirect('/')

def project_user_add(request, pk):
    if request.user.is_superuser:
        proj = Project.objects.get(id = pk)
        if request.method == 'POST':
            form = request.POST
            action = form.get('action')
            if action == 'Remove':
                for x in [int(i) for i in form if i.isdigit()]:
                    user = User.objects.get(id = x)
                    UserProject.objects.get(user=user, project=proj).delete()
            else:
                username = form.get('username')
                user = User.objects.get(username=username)
                UserProject(user=user, project=proj).save()
            return redirect(f'/projects/{pk}/')
        data = {}
        users = User.objects.filter(is_superuser=False)
        users_assigned = [i.user.username for i in UserProject.objects.filter(project=proj)]
        data['users'] = users.exclude(username__in=users_assigned)
        data['project'] = proj
        return render(request, 'RealtimeAPS/project_user_add.html', data)
    return redirect('/')

def project_sensor_add(request, pk):
    if request.user.is_superuser:
        proj = Project.objects.get(id = pk)
        if request.method == 'POST':
            form = request.POST
            action = form.get('action')
            if action == 'Remove':
                for x in [int(i) for i in form if i.isdigit()]:
                    Sensor.objects.get(id = x).delete()
            else:
                serial = form.get('serial')
                s_type = form.get('sensor_type')
                sensor = Sensor(serial = serial, type = s_type, project = proj)
                sensor.save()
            return redirect(f'/projects/{pk}/')
        data = {}
        data['project'] = proj
        return render(request, 'RealtimeAPS/project_sensor_add.html', data)
    return redirect('/')

RealtimeAPS/templates/RealtimeAPS/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>APS</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'RealtimeAPS/css/style.css' %}">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <!-- <script src="{% static 'RealtimeAPS/js/crazy.js' %}"></script> -->
    
    {% block required_script %}
        
    {% endblock %}
        
</head>

<body style="background-color: #e0fbfc;">
    <div class="w-100 bg-1 text-center position-fixed" style="z-index: 10;">
        <a class="nav-link" href="{% url 'RealtimeAPS:index' %}">
            <h1 class="fg-2 text-nowrap">APS Asia PDA Enterprise Pte Ltd.</h1>
        </a>
        {% if request.user.is_authenticated %}
            <div class="text-right pr-1 pb-1 m-t-35">
                <a href="{% url 'RealtimeAPS:logout' %}"><button>Log out</button></a>
            </div>
        {% endif %}
    </div>

    {% if request.path != "/login/" and request.user.is_superuser %}
        <div class="pt-75 pr-5 bg-3 h-100 position-fixed" style="right: 0;">
            <ul class="m-l-30" style="list-style: none;">
                <li>
                    <a class="nav-link fg-1" href="{% url 'RealtimeAPS:users' %}">User management</a>
                </li>
                <li>
                    <a class="nav-link fg-1" href="{% url 'RealtimeAPS:projects' %}">Projects</a>
                </li>
                <li>
                    <a class="nav-link fg-1" href="{% url 'DataManagement:data' %}">Data management</a>
                </li>
            </ul>
        </div>
    {% endif %}

    <div class="container-fluid pt-75">
        {% block body_block %}

        {% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>

</html>

RealtimeAPS/templates/RealtimeAPS/index.html
{% extends 'RealtimeAPS/base.html' %}

{% block body_block %}
    <div class="container-fluid w-100 pr-235 my-2">
        <form id="data-upload-form" action="{% url 'DataManagement:upload' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row h-100 rounded border border-dark pt-3">
                <div class="col-lg-3 col-md-6 col-12 h-100">
                    <div class="form-group">
                        <label for="project_name">Project Name</label>
                        <select id="proj_sel" class="form-control border-dark" name="project_name" onchange="update_sensors(this.value)">
                            
                            {% for p in projects %}
                                <option value="{{ p.name }}">{{ p.name }}</option>
                            {% endfor %}

                        </select>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 col-12 h-100">
                    <div class="form-group">
                        <label for="sensor_number">Sensor Number</label>
                        <select id="sensor_sel" class="form-control border-dark" name="sensor_number">
                            
                        </select>
                        <script type="text/javascript">
                            function update_sensors(proj) {
                                var data = JSON.parse("{{ sensors|escapejs }}");

                                var sel = document.querySelector("#sensor_sel");
                                while (sel.children.length != 0) {
                                    sel.removeChild(sel.lastElementChild);
                                }
                                for (var s in data[proj]) {
                                    var opt = document.createElement('option');
                                    opt.value = data[proj][s];
                                    opt.innerHTML = data[proj][s];
                                    sel.appendChild(opt);
                                }
                            }
                            var proj = document.querySelector("#proj_sel").value;
                            update_sensors(proj);
                        </script>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 col-12 h-100">
                    <div class="form-group">
                        <label for="data_file">Data File</label>
                        <input type="file" class="form-control-file" name="data_file">
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 col-12 h-100">
                    <label class="pb-3" for=""></label> <br>
                    <input class="btn border border-dark" type="submit" value="Upload">
                </div>
            </div>
        </form>
    </div>
    <div class="pr-235">
        <form class="pr-5" action="{% url 'RealtimeAPS:projects' %}" method="POST">
            {% csrf_token %}
            <h2>List of all projects</h2>
            <table class="table table-bordered table-sm">
                <thead class="bg-1" style="color: #e0fbfc;">
                    <tr>
                        <th scope="col" style="width: 250px;">Project name</th>
                        <th scope="col" style="width: 300px;">Usernames</th>
                        <th scope="col" style="width: 300px;">Sensors</th>
                    </tr>
                </thead>
                <tbody>
    
                    {% for p in projects %}
                    <tr>
                        <td><a href="{% url 'RealtimeAPS:project_detail' pk=p.pk %}">{{ p.name }}</a></td>
                        <td>
    
                            {% if p.projects.all %}
                            <select class="px-2 bg-2" name="username">
    
                                {% for u in p.projects.all %}
                                    <option value="{{ u.user.username }}">{{ u.user.username }}</option>
                                {% endfor %}
    
                            </select>
                            {% else %}
                            No assigned users
                            {% endif %}
    
                        </td>
                        <td>
    
                            {% if p.sensors.all %}
                                <select class="px-2 bg-2" name="sensor">
                                    
                                    {% for s in p.sensors.all %}
                                        <option>{{ s }}</option>
                                    {% endfor %}
                                        
                                </select>
                            {% else %}
                            No attached sensors
                            {% endif %}
    
                        </td>
                    </tr>
                    {% endfor %}
    
                </tbody>
            </table>
        </form>
    </div>
{% endblock %}

RealtimeAPS/templates/RealtimeAPS/project_add.html
{% extends 'RealtimeAPS/base.html' %}

{% block body_block %}
<div class="row">
    <div class="col-lg-4 col-md-6 col-8 container bg-1 rounded py-2 mt-2">
        <h2 class="text-center fg-2 mb-3">Create project</h2>
        <form id="login-form" class="m-auto" action="{% url 'RealtimeAPS:project_add' %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <input class="form-control" type="text" name="project_name" placeholder="Project name">
            </div>

            <input class="btn bg-2 mb-2" type="submit" value="Submit">
        </form>
    </div>
</div>
{% endblock %}

RealtimeAPS/templates/RealtimeAPS/project_detail.html
{% extends 'RealtimeAPS/base.html' %}

{% block body_block %}
<div class="pr-235">
    <form class="pr-5" action="{% url 'RealtimeAPS:project_detail' pk=project.pk %}" method="POST">
        {% csrf_token %}
        <h2>Edit project information</h2>
        <div class="list-action float-left">
            <input class="btn btn-sm btn-success" name="action" type="submit" value="Save">
            <input class="btn btn-sm btn-danger" name="action" type="submit" value="Cancel">
        </div>
        <div class="pl-2 mt-3">
            <div class="form-group row">
                <label class="col-lg-2 col-md-3 col-sm-4 col-12 col-from-label" for="project_name">Project name</label>
                <div class="col-lg-4 col-md-6 col-sm-8 col-12">
                    <input class="form-control form-control-sm border border-dark" type="text" name="project_name" value="{{ project.name }}">
                </div>
            </div>
        </div>
    </form>
    <form class="pr-5" action="{% url 'RealtimeAPS:assign' pk=project.pk %}" method="POST">
        {% csrf_token %}
        <h3>Users assigned</h3>
        
        {% if request.user.is_superuser %}
            <div class="list-action float-left">
                <a class="btn btn-sm btn-success" href="{% url 'RealtimeAPS:assign' pk=project.pk %}">Add</a>
                <input class="btn btn-sm btn-danger" name="action" type="submit" value="Remove">
            </div>
        {% endif %}

        <div style="width: 600px;">
            <table class="table table-bordered table-sm">
                <thead class="bg-1" style="color: #e0fbfc;">
                    <tr>
                        <th scope="col" style="width: 35px;">#</th>
                        <th scope="col" style="width: 200px;">Username</th>
                        <th scope="col" style="width: 350px;">Email</th>
                    </tr>
                </thead>
                <tbody>
            
                    {% for u in project.projects.all %}
                        <tr>
                            <td><input type="checkbox" name="{{ u.user.pk }}"></td>
                            <td><a href="{% url 'RealtimeAPS:user_detail' pk=u.user.pk %}">{{ u.user.username }}</a></td>
                            <td>{{ u.user.email }}</td>
                        </tr>
                    {% endfor %}
            
                </tbody>
            </table>
        </div>
    </form>
    <form class="pr-5" action="{% url 'RealtimeAPS:sensor_add' pk=project.pk %}" method="POST">
        {% csrf_token %}
        <h3>Sensors</h3>
        <div class="list-action float-left">
            <a class="btn btn-sm btn-success" href="{% url 'RealtimeAPS:sensor_add' pk=project.pk %}">Add</a>
            <input class="btn btn-sm btn-danger" name="action" type="submit" value="Remove">
        </div>
        <div style="width: 600px;">
            <table class="table table-bordered table-sm">
                <thead class="bg-1" style="color: #e0fbfc;">
                    <tr>
                        <th scope="col" style="width: 35px;">#</th>
                        <th scope="col" style="width: 200px;">Serial Number</th>
                        <th scope="col" style="width: 200px;">Sensor Type</th>
                        <th scope="col" style="width: 120px;">Upper Limit</th>
                        <th scope="col" style="width: 120px;">Lower Limit</th>
                    </tr>
                </thead>
                <tbody>
    
                    {% for s in project.sensors.all %}
                        <tr>
                            <td><input type="checkbox" name="{{ s.pk }}"></td>
                            <td><a href="{% url 'DataManagement:chart' serial=s.serial %}">{{ s.serial }}</a></td>
                            <td>{{ s.type }}</td>
                            <td>{{ s.up_lim_1 }}</td>
                            <td>{{ s.low_lim_1 }}</td>
                        </tr>
                    {% endfor %}
    
                </tbody>
            </table>
        </div>
    </form>
</div>
{% endblock %}

RealtimeAPS/templates/RealtimeAPS/project_sensor_add.html
{% extends 'RealtimeAPS/base.html' %}

{% block body_block %}
    <div class="row">
        <div class="col-lg-4 col-md-6 col-8 container bg-1 rounded py-2 mt-2">
            <h2 class="text-center fg-2 mb-3">Attach sensor</h2>
            <form id="login-form" class="m-auto" action="{% url 'RealtimeAPS:sensor_add' pk=project.pk %}" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <input class="form-control" type="text" name="serial" placeholder="Serial number">
                </div>
                <div class="form-group">
                    <select id="type_select" class="w-100 px-3" name="type" onchange="this.nextElementSibling.value=this.value">
                        <option value=""></option>
                        <option value="VM">VM</option>
                        <option value="TM">TM</option>
                        <option value="EL">EL</option>
                        <option value="TR">TR</option>                            
                    </select>
                    <input class="w-75" id="type_inp" type="text" name="sensor_type" value="" placeholder="Sensor type">
                </div>
    
                <input class="btn bg-2 mb-2" type="submit" value="Attach">
            </form>
        </div>
    </div>
{% endblock %}

RealtimeAPS/templates/RealtimeAPS/project_user_add.html
{% extends 'RealtimeAPS/base.html' %}

{% block body_block %}
    <div class="row">
        <div class="col-lg-4 col-md-6 col-8 container bg-1 rounded py-2 mt-2">
            <h2 class="text-center fg-2 mb-3">Assign user</h2>
            <form id="login-form" class="m-auto" action="{% url 'RealtimeAPS:assign' pk=project.pk %}" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <select class="form-control" name="username">
                        
                        {% for u in users %}
                            <option value="{{ u.username }}">{{ u.username }}</option>
                        {% endfor %}
                            
                    </select>
                </div>
    
                <input class="btn bg-2 mb-2" type="submit" value="Assign">
            </form>
        </div>
    </div>
{% endblock %}

RealtimeAPS/templates/RealtimeAPS/projects.html
{% extends 'RealtimeAPS/base.html' %}

{% block body_block %}
<div class="pr-235">
    <form class="pr-5" action="{% url 'RealtimeAPS:projects' %}" method="POST">
        {% csrf_token %}
        <h2>List of all projects</h2>
        <div class="list-action float-left">
            <input class="btn btn-sm btn-success" type="submit" name="action" value="Add">
            <input class="btn btn-sm btn-danger" type="submit" name="action" value="Remove">
        </div>
        <table class="table table-bordered table-sm">
            <thead class="bg-1" style="color: #e0fbfc;">
                <tr>
                    <th scope="col" style="width: 35px;">#</th>
                    <th scope="col" style="width: 250px;">Project name</th>
                    <th scope="col" style="width: 300px;">Usernames</th>
                    <th scope="col" style="width: 300px;">Sensors</th>
                </tr>
            </thead>
            <tbody>

                {% for p in projects %}
                    <tr>
                        <td><input type="checkbox" name="{{ p.pk }}"></td>
                        <td><a href="{% url 'RealtimeAPS:project_detail' pk=p.pk %}">{{ p.name }}</a></td>
                        <td>
                            
                            {% if p.projects.all %}
                                <select class="px-2 bg-2" name="username">
                                    
                                    {% for u in p.projects.all %}
                                        <option value="{{ u.user.username }}">{{ u.user.username }}</option>
                                    {% endfor %}

                                </select>
                            {% else %}
                                No assigned users
                            {% endif %}
                            
                        </td>
                        <td>

                            {% if p.sensors.all %}
                                <select class="px-2 bg-2" name="sensor">
                                    
                                    {% for s in p.sensors.all %}
                                        <option>{{ s }}</option>
                                    {% endfor %}
                                        
                                </select>
                            {% else %}
                                No attached sensors
                            {% endif %}
                            
                        </td>
                    </tr>
                {% endfor %}

            </tbody>
        </table>
    </form>
</div>
{% endblock %}

RealtimeAPS/templates/RealtimeAPS/user_add.html
{% extends 'RealtimeAPS/base.html' %}

{% block body_block %}
    <div class="row">
        <div class="col-lg-4 col-md-6 col-8 container bg-1 rounded py-2 mt-2">
            <h2 class="text-center fg-2 mb-3">Create user</h2>
            <form id="login-form" class="m-auto" action="{% url 'RealtimeAPS:user_add' %}" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <input class="form-control" type="text" name="username" placeholder="Username">
                </div>
                <div class="form-group">
                    <input class="form-control" type="email" name="email" placeholder="Email">
                </div>
                <div class="form-group">
                    <input class="form-control" type="password" name="password" placeholder="Password">
                </div>
    
                <input class="btn bg-2 mb-2" type="submit" value="Submit">
            </form>
        </div>
    </div>
{% endblock %}

RealtimeAPS/templates/RealtimeAPS/user_detail.html
{% extends 'RealtimeAPS/base.html' %}

{% block body_block %}
    <div class="pr-235">
        <form class="pr-5" action="{% url 'RealtimeAPS:user_detail' pk=user.pk %}" method="POST">
            {% csrf_token %}
            <h2>Edit user information</h2>
            <div class="list-action float-left">
                <input class="btn btn-sm btn-success" name="action" type="submit" value="Save">
                <input class="btn btn-sm btn-danger" name="action" type="submit" value="Cancel">
            </div>
            <div class="pl-2 mt-3">
                <div class="form-group row">
                    <label class="col-lg-2 col-md-3 col-sm-4 col-12 col-from-label" for="username">Username</label>
                    <div class="col-lg-4 col-md-6 col-sm-8 col-12">
                        <input class="form-control form-control-sm border border-dark" type="text" name="username" value="{{ user.username }}">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-lg-2 col-md-3 col-sm-4 col-12 col-from-label" for="email">Email</label>
                    <div class="col-lg-4 col-md-6 col-sm-8 col-12">
                        <input class="form-control form-control-sm border border-dark" type="text" name="email" value="{{ user.email }}">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-lg-2 col-md-3 col-sm-4 col-12 col-from-label" for="company_name">Company name</label>
                    <div class="col-lg-4 col-md-6 col-sm-8 col-12">
                        <input class="form-control form-control-sm border border-dark" type="text" name="company_name" value="{{ user.info.companyname }}">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-lg-2 col-md-3 col-sm-4 col-12 col-from-label" for="phone">Phone</label>
                    <div class="col-lg-4 col-md-6 col-sm-8 col-12">
                        <input class="form-control form-control-sm border border-dark" type="text" name="phone" value="{{ user.info.phone }}">
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

RealtimeAPS/templates/RealtimeAPS/users.html
{% extends 'RealtimeAPS/base.html' %}

{% block body_block %}
    <div class="pr-235">
        <form class="pr-5" action="{% url 'RealtimeAPS:users' %}" method="POST">
            {% csrf_token %}
            <h2>List of all users</h2>
            <div class="list-action float-left">
                <input class="btn btn-sm btn-success" type="submit" name="action" value="Add">
                <input class="btn btn-sm btn-danger" type="submit" name="action" value="Remove">
            </div>
            <table class="table table-bordered table-sm">
                <thead class="bg-1" style="color: #e0fbfc;">
                    <tr>
                        <th scope="col" style="width: 35px;">#</th>
                        <th scope="col" style="width: 200px;">Username</th>
                        <th scope="col" style="width: 260px;">Company name</th>
                        <th scope="col" style="width: 260px;">Email</th>
                        <th scope="col" style="width: 200px;">Phone</th>
                    </tr>
                </thead>
                <tbody>
                    
                    {% for u in users %}
                        <tr>
                            <td><input type="checkbox" name="{{ u.pk }}"></td>
                            <td><a href="{% url 'RealtimeAPS:user_detail' pk=u.pk %}">{{ u.username }}</a></td>
                            <td>{{ u.info.companyname }}</td>
                            <td>{{ u.email }}</td>
                            <td>{{ u.info.phone }}</td>
                        </tr>
                    {% endfor %}

                </tbody>
            </table>
        </form>
    </div>
{% endblock %}